
export enum ProjectStep {
  IDEATION = 'ideation',
  SCRIPT = 'script',
  THUMBNAIL = 'thumbnail',
  METADATA = 'metadata',
  EXPORT = 'export'
}

export type ScriptMode = 'auto' | 'manual' | 'winner';

export interface ScriptItem {
  id: string;
  title: string;
  script: string;
  status: 'pending' | 'generating' | 'completed' | 'failed';
  thumbStatus?: 'pending' | 'generating' | 'completed' | 'failed';
  thumbPrompt?: string;
  thumbMode?: 'auto' | 'manual';
  error?: string;
  thumbnails: string[];
  description?: string;
  chapters?: string;
  tags?: string;
  voiceStatus?: 'pending' | 'generating' | 'completed' | 'failed';
  voiceName?: string;
  audioUrl?: string;
}

export interface Project {
  id: string;
  name: string;
  niche: string;
  baseTheme: string;
  targetAudience: string;
  createdAt: string;
  items: ScriptItem[];
  globalTone: string;
  globalRetention: string;
  globalDuration: number;
  thumbnails: string[];
  scriptMode: ScriptMode;
  winnerTemplate?: string;
  positiveInstructions?: string;
  negativeInstructions?: string;
  script?: string;
  scriptPrompt?: string;
}

// --- VEO 3 TYPES ---

export interface VeoCharacter {
  id: string;
  nome: string;
  identidade: {
    sexo: string;
    faixa_etaria_aparente: string;
    etnia: string;
    tom_de_pele: string;
  };
  detalhes_rosto: {
    formato_do_rosto: string;
    cor_dos_olhos: string;
    sobrancelhas: string;
    tipo_de_nariz: string;
    boca_labios: string;
    marcas_faciais: string;
  };
  cabelo: {
    cor_do_cabelo: string;
    estilo_do_cabelo: string;
    pelos_faciais: string;
  };
  corpo: {
    altura_aproximada: string;
    tipo_fisico: string;
  };
  vestimenta: {
    roupas_principais: string;
    cores_predominantes: string;
  };
  presenca: {
    postura: string;
    expressao_facial_base: string;
    linguagem_corporal: string;
  };
}

export interface VeoLocation {
  id: string;
  nome_do_local: string;
  tipo_de_ambiente: 'interno' | 'externo';
  descricao_visual_detalhada: string;
  iluminacao_padrao: string;
  clima_atmosferico: string;
  elementos_fixos_importantes: string;
}

export interface VeoConsistency {
  personagens: VeoCharacter[];
  locais: VeoLocation[];
  epoca: {
    periodo_temporal: string;
    tecnologia_presente: string;
    estilo_visual_da_epoca: string;
  };
  tom_global: {
    estilo_narrativo: string;
    ritmo: string;
    clima_emocional: string;
    iluminacao_predominante: string;
    referencia_cinematografica: string;
  };
  roteiro_marcado: string;
}

export interface VeoScene {
  id: string;
  timestamp: string;
  prompt_base: string;
  isCopied: boolean;
}

export interface VeoProject {
  id: string;
  titulo: string;
  roteiro_original: string;
  consistency?: VeoConsistency;
  scenes?: VeoScene[];
  script_com_cenas?: string;
}

// --- APP SPECIFIC TYPES ---

/**
 * Represents a trending topic discovered by Trend Hunter
 */
export interface Trend {
  id: string;
  topic: string;
  reason: string;
  marketGap: string;
  viralScore: number;
  sources: { title: string; uri: string }[];
}

/**
 * Represents a title idea generated by the Title Generator
 */
export interface TitleIdea {
  id: string | number;
  title: string;
  ctrScore: string;
  tags: string[];
}

/**
 * Supported batch operation types
 */
export type BatchType = 'script' | 'thumbnail';

/**
 * Task definition for the batch processing engine
 */
export interface BatchTask {
  id: string;
  itemId: string;
  projectId: string;
  type: BatchType;
  status: 'pending' | 'processing' | 'completed' | 'failed' | 'cancelled';
  config?: any;
  error?: string;
}

/**
 * Global state of the batch processing system
 */
export interface BatchState {
  tasks: BatchTask[];
  isProcessing: boolean;
  currentTaskId: string | null;
  stats: {
    total: number;
    completed: number;
    failed: number;
    cancelled: number;
    percent: number;
  };
}
